import './js/api';
import './js/search';
import './js/today';
import './js/date';
import './js/quotes';
import './js/fiveDays';
import './js/moreInfo';
// import './js/chart';
// import './js/weather';
// import './js/favorite';